import numpy as np

leads = np.array([
    # s  m    t  w   th
    [12, 18, 10, 15, 5],   # facebook
    [20, 25, 22, 18, 8],   # insta
    [18, 30, 25, 22, 10],  # youtube
    [25, 28, 30, 26, 12],  # refferal
    [30, 35, 28, 32, 15],  # walkin
    [40, 45, 38, 40, 20],  # reddit
    [35, 50, 42, 45, 25]   # camp
    
])
#axis row =1
#axis column 2

#total leads generated by each day
total_leads=np.sum(leads,axis=0)
print(total_leads)

#total leads from each source
total_leads_row=np.sum(leads,axis=1)
print(total_leads_row)

# highest lead day
day_wise_total=np.sum(leads,axis=0)
max_total=np.max(day_wise_total)
print(np.argmax(day_wise_total))

# average leads per source
print(np.average(leads,axis=1))

# average leads per day
print(np.average(leads,axis=0))

# highest lead source
highest_lead_source=np.sum(leads,axis=1)
total_sources=np.max(highest_lead_source)
print(np.argmax(highest_lead_source))